STARTING_CASH = 100.0

# Forecasting / learning
FORECAST_HORIZON_MINUTES = 5
SCORING_INTERVAL_MINUTES = 5
DIRECTION_THRESHOLD = 0.58
QUANT_PRIOR = 0.90
LEARNED_PRIOR = 0.10
LEARNED_MAX = 0.25
LEARNED_MIN = 0.00
LEARNED_WARMUP = 100
LEARNED_MAX_STEP = 0.005
TOP_LEVEL_ETA = 0.05
TOP_LEVEL_SHARE = 0.02

# Quant-expert combiner
EXPERT_ETA = 0.05
EXPERT_SHARE = 0.03
EXPERT_MAX_WEIGHT = 0.60
EXPERT_MIN_WEIGHT = 0.05

# $100-account execution rails
PREFERRED_RISK_FRACTION = 0.15
HARD_RISK_FRACTION = 0.20
MAX_LEG_RELATIVE_SPREAD = 0.10
MAX_MONEYNESS_FRACTION = 0.02
MAX_SPREAD_WIDTH = 2.0
MIN_REWARD_RISK = 1.25
COOLDOWN_MINUTES = 5
MAX_HOLD_MINUTES = 15
STOP_LOSS_FRACTION = 0.35
TAKE_PROFIT_FRACTION = 0.50

# Webull base case for US equity options. Quoted bid/ask crossing remains in P&L.
FEE_PER_LEG_EACH_SIDE = 0.0

# Session controls
FIRST_SIGNAL_HOUR = 9
FIRST_SIGNAL_MINUTE = 45
LAST_SIGNAL_HOUR = 15
LAST_SIGNAL_MINUTE = 35
FORCE_FLAT_HOUR = 15
FORCE_FLAT_MINUTE = 45

# The already-inspected trailing year is research/development data, not a pristine holdout.
BACKTEST_START = (2025, 10, 1)
BACKTEST_END = (2026, 9, 30)
